### PR TITLE
Tutorial mendes

### PR DESCRIPTION
**Pull request by felipebmendes**
#### Please provide details about this Pull Request (why the change is being made, what this commit will do):

Merging online app tutorials to tutorial branch.

### CODE REVIEW

**Comment by rafarui** [comment]
I think it is a good idea to merge master to this tutorial, it might have many conflicts latter when try to merge this to master.

**Comment by felipebmendes** [comment]
> I think it is a good idea to merge master to this tutorial, it might have many conflicts latter when try to merge this to master.

@rafarui  It has been merged already. The merge is being blocked because of the PR's size.

**Comment by felipebmendes** [comment]
> I think it is a good idea to merge master to this tutorial, it might have many conflicts latter when try to merge this to master.

@rafarui  It has been merged already. The merge is being blocked because of the PR's size.

**Review by JuvenalDuarte — APPROVED** [review]

**Comment by JuvenalDuarte** [comment]
Merging revisions on the UI app made by mendes.

**Pull request merged**
